### ISSUE TITLE
`no_std` support

### ISSUE THREAD

**Issue by indietyp** [mhogrefe/malachite#10]
I am currently working on an embedded project where the `std` isn't available. I understand that for numbers larger than $2^{64}$, numbers will need to allocate, but `alloc` is available on my platform.

After a cursory at the library and import statements, it seems a conversion to a `no-std` compatible library would be possible?

I this something this library would be willing to support?

I'd be happy to create a PR converting the project to `no-std`!

**Comment by mhogrefe** [comment]
Thank you for the suggestion and your PR offer!

I think this would a useful change. After doing some quick research into `no-std`, converting Malachite to it does seem possible. Malachite uses `Vec` very often and occasionally uses `Box`, but the `alloc` crate lets you use those. Malachite also uses `HashMap` in a few places, but it should be possible to use the [hashbrown](https://crates.io/crates/hashbrown) `HashMap` instead. The test code, as well as anything enabled with `bin_util` and `test_util`, doesn't need to be converted.

Please go ahead with the PR, and let me know if you run into any issues.

**Comment by indietyp** [comment]
I am sorry that not much has moved in this regard. I started to work on this, but then the needs of the particular no-std project shifted to no longer require this library and I kind of forgot to complete and submit a PR 😅 Sorry!
