### ISSUE TITLE
Update `rand` + other dependencies in Cargo.toml

### ISSUE THREAD

**Issue by HastD** [mhogrefe/malachite#11]
The dependencies `rand`, `rand_chacha`, `itertools`, and `sha3` all have new minor versions that, due to being "0.x" releases, require an update to Cargo.toml to use. The new versions are: `rand 0.8`, `rand_chacha 0.3`, `itertools 0.10`, and `sha3 0.10`. These include various bug fixes and performance improvements, and it seems like a good idea to update Malachite to use these.

This doesn't seem to break any tests—I edited the Cargo.toml files on a local copy and ran `cargo test --release --features test_build`, which I'm assuming runs all the tests (I'm not too familiar with Malachite's codebase so I wasn't totally sure). Updating to the latest version of these widely used crates would also make it less likely that crates using Malachite will have to compile multiple versions of these dependencies. For example, some of my code that uses Malachite currently has to compile both `rand 0.8` and `0.7` as dependencies, which adds extra compilation time.

(Great work on this crate, by the way! Part of my code is about 4 times faster with Malachite than with `num`.)

**Comment by mhogrefe** [comment]
Ok, I'll include an upgrade in the next release. Thanks for running the tests, I know they take a while.
