### ISSUE TITLE
idea: const literals

### ISSUE THREAD

**Issue by OliverNChalk** [mhogrefe/malachite#16]
How do you feel about supporting const literals for `Natural` and `Rational` up to limit `u64::MAX` and `u64::MAX/u64::MAX` respectively? This could be implemented via:

- `const fn natural_literal(val: u64) - > Natural`
- `const fn rational_literal(val: u64) -> Rational`

In an ideal world, the `From` trait would cover this for cases where the conversion function only uses const allow operations, alas, we do not live in such world.

**Comment by mhogrefe** [comment]
Good idea. I'll implement this in the version of Malachite after the next one.

It should be possible to do something like `const fn rational_literal(n: u64, d: u64)` too. It would return an Option to handle the d == 0 case, and for reducing the numerator and denominator I could write a const GCD function that uses the Euclidean algorithm unrolled to a fixed depth. The tricky part would be determining which depth is sufficient for all `(u64, u64)` inputs.

**Comment by novafacing** [comment]
I'd also love this, I'm using malachite for some code generation right now, where being able to offload all the (10s of thousands of) constants to compile time would be significant for performance.

**Comment by mhogrefe** [comment]
I was saving this for a large release later, but I've decided to push it out in [0.4.2](https://github.com/mhogrefe/malachite/releases/tag/v0.4.2) so I don't keep you waiting.
