### ISSUE TITLE
Make randomness features optional

### ISSUE THREAD

**Issue by konstin** [mhogrefe/malachite#26]
It would be great if the randomness features, especially the `sha3` dependency, would become optional. We don't use any non-deterministic features and this would make malachite a much more lightweight crate.

**Comment by mhogrefe** [comment]
Fixed in 0.4.3. Randomness is now behind an optional `random` feature.

**Comment by mhogrefe** [comment]
Sorry, v0.4.3 had some wrong dependencies. Please use v0.4.4 instead.
