### ISSUE TITLE
missing way to convert digits part of rational to integer?

### ISSUE THREAD

**Issue by ThomasCartier** [mhogrefe/malachite#30]
Hi,
using `digits` from a rational enables to separate the integer [digits from the decimal part](https://docs.rs/malachite/latest/malachite/struct.Rational.html#examples-6).
Now converting that integer part to an Integer is not easy because we may have multiple naturals (why not a single extensible natural? Feature request?) coming from the `Vec<Natural>`.
in the example it's "[3]", but what if it becomes "[3, 10]" or anything else/longer ?

Is there a way to  convert the result to an Integer, for further calculation or storage ?
The goal is Integer approximation of the rational.

Thanks!

**Comment by mhogrefe** [comment]
Hi Thomas,

If you want to get the integer part of a `Rational`, I recommend using [an implementation of RoundingFrom](https://docs.rs/malachite-q/latest/malachite_q/struct.Rational.html#impl-RoundingFrom%3CRational%3E-for-Integer), like this:

```
import malachite::num::conversion::traits::RoundingFrom;
import malachite::rounding_modes::RoundingMode;

let n = Integer::rounding_from(Rational::from_signeds(22, 7), RoundingMode::Down).0;
assert_eq!(n, 3);
```

`RoundingMode::Down` rounds towards 0. `rounding_from` returns a pair whose second element is an `Ordering`, so you can use `.0` to just get the integer.

In this example, `rounding_from` takes ownership of the `Rational`, but you can also call it on `&Rational`.

Another option is using an implementation of [`Floor`](https://docs.rs/malachite/latest/malachite/struct.Rational.html#impl-Floor-for-%26Rational), but calling it on -3.5 will give you -4, which may not be what you want.

The `digits` function splits the both the integer part and the fractional part into digits. It sounds like you don't want that.

**Comment by ThomasCartier** [comment]
Thanks for your answer, much appreciated! (As your library is 👍)
