### ISSUE TITLE
From implementations panic - use TryFrom instead

### ISSUE THREAD

**Issue by Andlon** [mhogrefe/malachite#4]
The current `From` impls for `From<f64> for Rational` panics if it encounters a NaN or infinity. It is documented to do so in the `impl`, however it is a violation of the `From` contract as stipulated by the [`From` trait](https://doc.rust-lang.org/stable/std/convert/trait.From.html):

> Note: This trait must not fail. The From trait is intended for perfect conversions. If the conversion can fail or is not perfect, use [TryFrom](https://doc.rust-lang.org/stable/std/convert/trait.TryFrom.html).

So it seems that these impls should rather be `TryFrom` instead.

**Comment by mhogrefe** [comment]
Fixed in Malachite 0.3.0. I also replaced `CheckedFrom` by `TryFrom` everywhere.
