### ISSUE TITLE
Inconsistency between code and comments

### ISSUE THREAD

**Issue by YichiZhang0613** [mhogrefe/malachite#45]
I found some inconsistency between code and comments.
In malachite-master/malachite-nz/src/natural/random/mod.rs, the comments "Panics ... or if $a > b$"indicate that there is a constraint a <= b. However, the code uses `assert!(a < b);` to check it.
```rust
/// # Panics
/// Panics if `mean_stripe_denominator` is zero, if `mean_stripe_numerator <=
/// mean_stripe_denominator`, or if $a > b$.
#[inline]
pub fn striped_random_natural_range(seed: Seed, a: Natural, b: Natural, mean_stripe_numerator: u64, mean_stripe_denominator: u64,) -> StripedRandomNaturalInclusiveRange {
    assert!(a < b);
```
In malachite-master/malachite-q/src/exhaustive/mod.rs, the comments "Panics ... or if $a < b$"indicate that there is a constraint a >= b. However, the code uses `assert!(a <= b);` to check it.
```rust
/// # Panics
/// Panics if `d` is zero or if $a < b$.
pub fn exhaustive_rationals_with_denominator_inclusive_range(
    d: Natural,
    a: Rational,
    b: Rational,
) -> RationalsWithDenominator<ExhaustiveIntegerRange> {
    assert_ne!(d, 0u32);
    assert!(a <= b);
```
In malachite-master/malachite-nz/src/natural/arithmetic/div.rs, the comments indicate the comment other != 0 while the code doesn't check it. There are a lot of similar cases in this file and malachite-master/malachite-nz/src/integer/arithmetic/div.rs and malachite-master/malachite-nz/src/natural/arithmetic/mod_op.rs 
```rust
/// # Panics
/// Panics if `other` is zero.
fn div(mut self, other: Natural) -> Natural {
        self /= other;
        self
    }
```

**Comment by mhogrefe** [comment]
Thanks for catching the inconsistencies in the `a` and `b` assertions. I fixed them as part of v0.4.11.

That `div` implementation example does panic; it forwards to the `div_assign` implementation, which has an [explicit panic](https://github.com/mhogrefe/malachite/blob/master/malachite-nz/src/natural/arithmetic/div.rs#L2231). There is a unit test for this situation [here](https://github.com/mhogrefe/malachite/blob/master/malachite-nz/src/natural/arithmetic/div.rs#L2231).

Likewise, the `Integer` division and modulo functions forward to the `Natural` division and modulo functions, which panic.
