### ISSUE TITLE
Will decimal point numbers ever be supported?

### ISSUE THREAD

**Issue by DarkLord76865** [mhogrefe/malachite#5]
Hi,
I am interested in using this crate in my projects. Especially because I can't get rug crate to work, and according to benchmarks this is just a little slower. The thing is I need to calculate something with decimal point numbers (with set precision) (like PI with decimal precision 5 -> 3.1415). As I understand rug allows this by linking to C MPFR library, but as I said rug won't compile for me, no matter what I do so are there any plans to implement this in Rust (in this crate)?

Anyway, keep up good work!
Regards

**Comment by mhogrefe** [comment]
Thanks!

Yes, I will start implementing arbitrary-precision floats soon. I will be following the MPFR interface pretty closely, so anything that MPFR (and rug) supports, Malachite eventually will too.

But I want to point out that none of these implementations are actually decimal-based. Any approximation of pi that these libraries work with is a "dyadic rational", or a multiple of an integer power of 2. For example, one such approximation is 11.00100100001111110110, which is 3.1415920257568359375 exactly and may be rounded to "3.1415", "3.1416", or something else, depending on how you choose to round it. If you specifically want a decimal-based library, those do exist. One is https://github.com/paupino/rust-decimal.

**Comment by DarkLord76865** [comment]
Thanks for all the work you are doing!
And thanks for clarifying how these libraries work. I think I will be able to work with it. You got a star from me 👍
